FROM python:3.10 as build
WORKDIR /build

RUN curl -sSL https://install.python-poetry.org | python -
ENV PATH /root/.local/bin:$PATH
COPY pyproject.toml poetry.lock ./
RUN poetry export -f requirements.txt --output requirements.txt --without-hashes --with server --without dev

FROM python:3.10-slim

WORKDIR /app
COPY --from=build /build/requirements.txt ./

RUN pip3 install -r requirements.txt
COPY ./src/fastapi_server .

EXPOSE 80

HEALTHCHECK CMD curl --fail http://localhost:80/_stcore/health

ENTRYPOINT ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "80"]
